AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Firehose DeliveryStream S3 Destination.
Parameters:
  WAFLogS3Bucket:
    Type: String
  FirewallManagerAccount:
    Type: String
  KMSKeyArn:
    Type: String
    Default: <na>
Conditions:
  KMSEncryption: !Not[!Equals[!KMSKeyArn, '<na>']]
Resources:
  WAFDeliveryLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/kinesisfirehose
  WAFDeliveryLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: /aws/kinesisfirehose
      LogStreamName: !Ref WAFdeliverystream
  WAFdeliverystream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "aws-waf-logs-delivery-${FirewallManagerAccount}-${AWS::Region}"
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub "arn:aws:s3:::${WAFLogS3Bucket}"
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: /aws/kinesisfirehose
          LogStreamName: !Sub "aws-waf-logs-delivery-${FirewallManagerAccount}-${AWS::Region}"
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 50
        CompressionFormat: UNCOMPRESSED
        EncryptionConfiguration:
          KMSEncryptionConfig:
            AWSKMSKeyArn: !If [KMSEncryption, !Ref KMSKeyArn, !Ref "AWS::NoValue"]
        Prefix: !Sub 'firehose/${AWS::AccountId}/${AWS::Region}/'
        RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/KinesisFirehoseWafDeliveryRole"
